### ISSUE TITLE
The README has a bunch of broken links (to demos).

### ISSUE THREAD

**Issue by 7ombie** [STREGAsGate/GateEngineDemos#7]
When you click on three of the hyperlinks in the README that link to the individual demos, you get a GitHub 404 page instead. The first three demos (*User Input*, *Multiple Windows* and *Save State*) have broken links. The links for the 2D and 3D demos are fine.

**Comment by mgrider** [comment]
I opened a PR (#9) to fix these, but you can just open the Sources folder to see what's in there: https://github.com/STREGAsGate/GateEngineDemos/tree/main/Sources

**Comment by STREGA** [comment]
Fixed in #9.
