### ISSUE TITLE
Error in `IOKitGamePadInterpreter.swift` causes build failure

### ISSUE THREAD

**Issue by mgrider** [STREGAsGate/GateEngineDemos#8]
I'm seeing the following error:

> `Access level on imports require '-enable-experimental-feature AccessLevelOnImport'`

I first saw it in my own project after updating to 0.2.0, but it also happens when I try and build this demo repo. I can build again by reverting my project to GateEngine 0.1.2.

**Comment by STREGA** [comment]
Fixed in new release v0.2.1
